version: '3'
services:
  multi:
    build: .
    container_name: multi
    env_file:
      - .env
    networks:
      - deploy
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

networks:
  deploy:
    external : true

