version: '3'
services:
  member_dev:
    build: ./Member
    container_name: member_dev
    env_file:
        .env
    networks:
      - deploy
    ports:
      - "8080:8080"

networks:
  deploy:
    driver: bridge
